CREATE TABLE LINKS_TO_BE_PROCESSED (LINK VARCHAR(10000));
CREATE TABLE LINKS_ALREADY_PROCESSED (LINK VARCHAR(10000));
CREATE TABLE NEWS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE TEXT,
    CONTENT TEXT,
    URL VARCHAR(10000),
    CREATED_AT TIMESTAMP,
    MODIFIED_AT TIMESTAMP
);